# To opt-in to new RuboCop cops by default, add the following to your .rubocop.yml:
#
AllCops:
  NewCops: enable

# Then, configure the new cops as needed. Example:

Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/AttributeAssignment:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
Layout/EmptyLinesAfterModuleInclusion:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
