kpis = KPIService.new(@project)
json.asu kpis.find_kpi(:asu)
json.asps kpis.find_kpi(:asps)
json.asic kpis.find_kpi(:asic)
json.asr kpis.find_kpi(:asr)
json.ftu kpis.find_kpi(:ftu)
json.ftps kpis.find_kpi(:ftps)
json.ftic kpis.find_kpi(:ftic)
json.ftr kpis.find_kpi(:ftr)
json.ene kpis.find_kpi(:ene)
json.eip kpis.find_kpi(:eip)
json.ec kpis.find_kpi(:ec)
